export const SEED_KNOWLEDGE = [
  {
    id: "predikta_non_technical_description",
    text: "Predikta is a behavioral AI platform that simulates how real audiences will respond to messages, ideas, and decisions before anything goes live. It combines generative AI with behavioral science to model sentiment, emotion, and motivation at scale.",
    metadata: {
      source_id: "predikta_non_technical_description",
      source: "predikta_non_technical_description",
      source_name: "Predikta Description (Non-technical)",
      visibility: "public",
      topic: "overview",
    },
  },
  {
    id: "predikta_external_faq_difference",
    text: "Predikta is proactive rather than reactive. Standard tools show what happened in the past or who the audience is demographically, while Predikta is designed to explain why people will react and how they are likely to respond before media spend happens.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "faq",
    },
  },
  {
    id: "predikta_internal_faq_limits",
    text: "Predikta can gauge sentiment around campaign messaging, but it should not be framed as a tool that directly predicts sensory experience, exact buying behavior, or split-second in-the-moment decisions without richer context.",
    metadata: {
      source_id: "predikta_internal_faq",
      source: "predikta_internal_faq",
      source_name: "Predikta FAQ - Can/Can't Do (Internal)",
      visibility: "internal",
      topic: "capabilities_and_limits",
    },
  },
  {
    id: "predikta_internal_faq_segmentation",
    text: "Predikta can segment audiences by location, age group, socioeconomic status, and occupation, and can also distinguish generations such as Gen Z, Millennials, and Gen X. Granularity can decrease representation quality at narrower geographic levels.",
    metadata: {
      source_id: "predikta_internal_faq",
      source: "predikta_internal_faq",
      source_name: "Predikta FAQ - Can/Can't Do (Internal)",
      visibility: "internal",
      topic: "segmentation",
    },
  },
  {
    id: "predikta_external_faq_personas",
    text: "Predikta supports highly specific audiences by combining demographic filters such as location, income, and occupation with psychographic refinement, including persona types like budget-conscious or research-driven consumers.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "personas",
    },
  },
  {
    id: "predikta_external_faq_outputs",
    text: "Predikta outputs a behavioral intelligence report with sentiment and emotion signals, relevance and purchase-intent indicators, and narrative analysis that can show where attention drops or emotions peak in scripts.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "outputs",
    },
  },
  {
    id: "predikta_use_cases_validation",
    text: "Predikta supports pre-launch campaign idea validation for broad concepts, slogans, and brand promises. It can surface early signals of relevance, strength, and misalignment before execution.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_comparison",
    text: "Predikta can compare multiple creative routes or messaging approaches to show which direction performs best across segments, helping teams converge on stronger messaging with evidence instead of opinion.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_copy_testing",
    text: "Predikta supports execution-level copy testing and optimization, including headlines, body copy, calls to action, and script or narrative evaluation before launch.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_external_faq_timing",
    text: "Predikta is useful at strategic planning, creative comparison, execution testing, and video or script testing stages. It is intended to help teams refine campaigns before launch rather than waiting for live A/B results.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "campaign_stages",
    },
  },
  {
    id: "predikta_dictionary_traits",
    text: "Predikta uses personality-related constructs such as extraversion, conscientiousness, agreeableness, emotionality, and openness to experience.",
    metadata: {
      source_id: "predikta_bs_dictionary",
      source: "predikta_bs_dictionary",
      source_name: "BS Dictionary",
      visibility: "internal",
      topic: "terminology",
    },
  },
  {
    id: "predikta_external_faq_security",
    text: "Predikta frames security around logical client data isolation, encryption at rest and in transit, and AWS-hosted infrastructure. Highly specific security, legal, or privacy commitments should still be handled by the team.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "security",
    },
  },
  {
    id: "predikta_external_faq_blindspot",
    text: "Predikta addresses the 'billion dollar blindspot' in marketing and innovation by helping teams move from guesswork toward forward-looking behavioral insight before they spend budget.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "value_proposition",
    },
  },
  {
    id: "predikta_external_faq_data_source",
    text: "Predikta's data comes from a national psychographic survey across Philippine regions. The system can also take additional context so simulations are better fitted to a specific campaign situation.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "methodology",
    },
  },
  {
    id: "predikta_external_faq_accuracy",
    text: "Predikta is presented as maintaining 95 percent trait alignment with real humans and 88 percent accuracy in consumer sentiment simulation.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "methodology",
    },
  },
  {
    id: "predikta_external_faq_probabilistic",
    text: "Predikta should be framed as providing probabilistic behavioral signals that augment human decision-making rather than deterministic predictions.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "methodology",
    },
  },
  {
    id: "predikta_external_faq_social_bias",
    text: "Compared with traditional surveys, Predikta is positioned as reducing social desirability bias because its behavioral agents are grounded in stable psychographic traits rather than aspirational self-reporting.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "methodology",
    },
  },
  {
    id: "predikta_external_faq_ab_testing",
    text: "Predikta differs from standard A/B testing because it helps simulate audience reaction before launch, rather than waiting for live media spend and reactive performance data.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "comparison",
    },
  },
  {
    id: "predikta_external_faq_visual_limit",
    text: "Predikta currently supports scripts, copy sheets, slogans, and broad concepts. It does not clearly claim full multimodal image or video understanding in the public material.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "limitations",
    },
  },
  {
    id: "predikta_external_faq_programs",
    text: "Predikta's program management concept is framed as a way to track performance across a series of coordinated, goal-driven campaigns rather than a single isolated campaign test.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "platform",
    },
  },
  {
    id: "predikta_external_faq_optional_data",
    text: "Clients do not have to upload their own customer data to get started because Predikta is framed as being pre-loaded with national-level behavioral data.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "data_requirements",
    },
  },
  {
    id: "predikta_external_faq_dialects",
    text: "The underlying survey was translated into five major dialects including Tagalog, Cebuano, Ilocano, Bicolano, and Ilonggo.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "language",
    },
  },
  {
    id: "predikta_external_faq_turnaround",
    text: "Predikta is described as typically taking around one to three minutes for simulation results rather than being fully real-time at scale.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "operations",
    },
  },
  {
    id: "predikta_external_faq_chatgpt_difference",
    text: "ChatGPT guesses a persona from internet text, while Predikta is positioned as a behavioral model grounded in proprietary psychographic profiles of Filipino consumers.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "comparison",
    },
  },
  {
    id: "predikta_external_faq_social_listening",
    text: "Predikta is framed as complementary to social listening: social listening tells you what happened after the fact, while Predikta helps you think about why it may happen before spending budget.",
    metadata: {
      source_id: "predikta_external_faq",
      source: "predikta_external_faq",
      source_name: "FAQs for Predikta",
      visibility: "public",
      topic: "comparison",
    },
  },
  {
    id: "predikta_internal_faq_personas",
    text: "Predikta can generate consumer personas by grouping people with similar psychographic profiles. The internal FAQ describes these personas as more unique than traditional ones because they combine demographics with values, motivations, and personality-driven understanding.",
    metadata: {
      source_id: "predikta_internal_faq",
      source: "predikta_internal_faq",
      source_name: "Predikta FAQ - Can/Can't Do (Internal)",
      visibility: "internal",
      topic: "personas",
    },
  },
  {
    id: "predikta_internal_faq_marketing_drivers",
    text: "The internal FAQ says Predikta can identify which demographic and psychographic characteristics drive behaviors like materialism, impulsive buying, and exploratory buying, helping teams understand not just who consumers are but why they engage.",
    metadata: {
      source_id: "predikta_internal_faq",
      source: "predikta_internal_faq",
      source_name: "Predikta FAQ - Can/Can't Do (Internal)",
      visibility: "internal",
      topic: "marketing_drivers",
    },
  },
  {
    id: "predikta_internal_faq_communication_approach",
    text: "The internal FAQ says Predikta can provide campaign messaging suggestions because it combines consumer profiling with marketing drivers, enabling communication strategies that align with motivation and decision-making style.",
    metadata: {
      source_id: "predikta_internal_faq",
      source: "predikta_internal_faq",
      source_name: "Predikta FAQ - Can/Can't Do (Internal)",
      visibility: "internal",
      topic: "communication",
    },
  },
  {
    id: "predikta_internal_faq_synthetic_population",
    text: "The internal FAQ says Predikta generated around 17,000 synthetic Filipino profiles from roughly 3,000 nationally representative respondents while aiming to preserve demographic structure and psychographic correlations.",
    metadata: {
      source_id: "predikta_internal_faq",
      source: "predikta_internal_faq",
      source_name: "Predikta FAQ - Can/Can't Do (Internal)",
      visibility: "internal",
      topic: "synthetic_data",
    },
  },
  {
    id: "predikta_use_cases_objective_simulation",
    text: "Predikta can replace subjective internal debate with objective simulation, giving teams data-backed sentiment and behavioral response signals for each creative version.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_iteration_speed",
    text: "Predikta is positioned as shortening slow feedback loops by giving teams simulation-based iteration before focus groups, surveys, or live launch feedback would normally arrive.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_demographic_trap",
    text: "Predikta helps teams escape the demographic trap by going beyond age, gender, and location to simulate responses through values, beliefs, and motivations.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_crisis_comms",
    text: "Predikta can also be used for crisis communications, helping teams test multiple versions of a PR statement to see which language is more likely to reduce tension rather than worsen outrage.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_influencer_fit",
    text: "Predikta is positioned as helping with influencer or KOL fit by testing whether a creator's narrative and tone align with a target audience's values, affinity, and perception.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_incentives",
    text: "Predikta can help with incentive optimization by testing whether different frames like exclusive access, savings, scarcity, or status trigger stronger persuasion for different segments.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "use_cases",
    },
  },
  {
    id: "predikta_use_cases_oppo",
    text: "For OPPO, the use case sheet suggests segmenting high-income aspirationals versus value-driven practicalists, then testing premium AI lifestyle messaging against durability and battery-life messaging before launch.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "industry_examples",
    },
  },
  {
    id: "predikta_use_cases_ipeople",
    text: "For iPeople schools, the use case sheet suggests hyper-segmented enrollment messaging, testing narratives like prestige, job readiness, and innovation against different student and parent psychographic profiles.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "industry_examples",
    },
  },
  {
    id: "predikta_use_cases_asialink",
    text: "For Asialink Finance, the use case sheet suggests testing whether collateral-based loan messaging should lead with lowest rates or fastest approval, then using simulated entrepreneur reactions to choose the stronger hook.",
    metadata: {
      source_id: "predikta_use_cases",
      source: "predikta_use_cases",
      source_name: "[PREDIKTA] Use Cases Sheet",
      visibility: "public",
      topic: "industry_examples",
    },
  },
  {
    id: "predikta_investor_overview",
    text: "Predikta is presented to investors as behavioral intelligence for Southeast Asia, starting with the Philippines. The pitch frames it as a way to simulate how audiences will respond to campaigns and concepts before launch, using published behavioral science rather than generic prompting.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_overview",
    },
  },
  {
    id: "predikta_investor_problem",
    text: "Brands often launch blind because traditional market research takes three to four weeks, costs roughly one hundred thousand to one hundred twenty thousand pesos per study, and often arrives too late to improve the campaign that needed the insight.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_thesis",
    },
  },
  {
    id: "predikta_investor_product",
    text: "The workflow takes a campaign brief or message, selects a Filipino psychographic segment, runs behavioral simulation across a large modeled population, and returns predicted sentiment plus directional recommendations in hours.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_overview",
    },
  },
  {
    id: "predikta_investor_validation",
    text: "Predikta separates lab validation from commercial validation. Published results support trait alignment and survey-style sentiment accuracy, while the next major proof point is whether simulation outputs consistently predict real-world campaign outcomes at commercial scale.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_validation",
    },
  },
  {
    id: "predikta_investor_soft_launch",
    text: "Predikta entered a controlled soft launch in late February 2026, using that phase to test the product, refine workflows, and gather early customer validation before full go-to-market.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_traction",
    },
  },
  {
    id: "predikta_investor_traction",
    text: "Predikta reached around seventy thousand pesos in monthly recurring revenue during soft launch, with three paying clients, five active enterprise pilots, and more than thirty product testers before full commercial launch.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_traction",
    },
  },
  {
    id: "predikta_investor_repeat_usage",
    text: "A major early traction signal in the investor material is that all three paying soft-launch clients came back for additional simulations, suggesting repeat workflow value rather than one-off novelty.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_traction",
    },
  },
  {
    id: "predikta_investor_raise",
    text: "The raise is framed as a one point five million dollar seed round on a SAFE with a six million dollar valuation cap. Globe and 917Ventures are presented as the lead or anchor with a signed term sheet.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_raise",
    },
  },
  {
    id: "predikta_investor_use_of_funds",
    text: "The round is meant to fund full commercial launch, with allocation across sales and customer success, product and engineering, dataset enrichment, and validation plus operations.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_raise",
    },
  },
  {
    id: "predikta_investor_moat",
    text: "The investor case for defensibility centers on an accuracy feedback loop from real outcomes, localization infrastructure built on Philippine behavioral data, culturally calibrated psychographic modeling, and strategic distribution access through Globe and 917Ventures.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_moat",
    },
  },
  {
    id: "predikta_investor_conditions",
    text: "Three things still need to be proven: simulations must predict real campaign outcomes, customers must use Predikta repeatedly, and localized Filipino models must outperform generic AI approaches in practice.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_validation",
    },
  },
  {
    id: "predikta_investor_team",
    text: "The team story combines repeat founder experience and scientific depth. Axel Kornerup is presented as a repeat founder with netopia and InterVenn background, while Jason Albia is presented as the computational scientist behind the psychographic simulation architecture and published validation work.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_team",
    },
  },
  {
    id: "predikta_investor_roadmap",
    text: "The 2026 roadmap on the investor page focuses on full commercial launch, converting pilots to recurring accounts, publishing the two-hundred-plus campaign validation study, building a repeatable sales motion, and creating the proof base for a disciplined Series A conversation.",
    metadata: {
      source_id: "predikta_investor_site",
      source: "predikta_investor_site",
      source_name: "Predikta Investor Website",
      visibility: "public",
      topic: "investor_roadmap",
    },
  },
];
